# Generated by Django 3.2.7 on 2021-12-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.FloatField(primary_key=True, serialize=False)),
                ('video', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
